name: "End-to-end tests with Playwright"
description: "Setup Playwright and run end-to-end tests"

inputs:
  test-timeout:
    description: "Timeout for running Playwright tests (in minutes)"
    required: false
    default: 3
  continue-on-error:
    description: "Continue on error for Playwright tests"
    required: false
    default: true
  trace:
    description: "Enable tracing for Playwright tests"
    required: false
    default: "on"

runs:
  using: "composite"
  steps:
    - name: Install Playwright and Chromium
      run: npx playwright install chromium --with-deps
      shell: bash

    - name: Run Playwright tests
      env:
        TIMEOUT: ${{ inputs.test-timeout }}
      run: npx playwright test --reporter="list,html" --project=chromium --trace=${{ inputs.trace }} --retries=${{ inputs.retries }} --global-timeout=$(( $TIMEOUT * 60 * 1000 ))
      continue-on-error: true
      shell: bash

  