on: [push]

jobs:
  setup-playwright:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: End-to-end tests with Playwright
        uses: testiautomaatio/playwright-action@main
